server:
  port: 8080

ping:
  environment-id: ${PING_ENV_ID}

spring:
  security:
    oauth2:
      client:
        provider:
          nauth:
            user-name-attribute: name
            issuer-uri: http://localhost:9090/auth/realms/test-realm
          pingidentity:
#            user-name-attribute: name
            issuer-uri: https://auth.pingone.eu/${ping.environment-id}/as
        registration:
          nauth:
            client-id: test-client
            client-secret: c582f8c2-2f92-4066-8128-e23276ad64b7
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope: openid
          pingidentity:
            client-id: ${PING_CLIENT_ID}
            client-secret: ${PING_CLIENT_SECRET}
            provider: pingidentity
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope: email,openid
            redirect-uri: http://localhost:8080/login/oauth2/code/pingidentity
  cloud:
    gateway:
      routes:
        - id: be-test-service
          uri: http://localhost:8081
          # Path to the sample be resource service
          predicates:
            - Path=/test-resource/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie