spring:
  cloud:
#    function:
#      definition: loggingConsumer
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        loggingConsumer-in-0:
          group: test_group
          destination: data_stream
          contentType: application/json
        eventProducer-out-0:
          destination: data_stream
          contentType: application/json